controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    robotiq_gripper_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

      
robotiq_gripper_controller:
  ros__parameters:
    joint: robotiq_85_left_knuckle_joint
